name: authentication_repository
description: Dart package which manages the authentication domain
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  http_client_adapter:
    path: ../../infra/http_client

dev_dependencies:
  very_good_analysis: ^3.1.0



